#!/bin/bash

TAG=v0.0.0.7

git checkout $TAG
#git stash pop
npm i
gulp js
docker build -t abstractalchemist/deck-builder -f Dockerfile .
docker push abstractalchemist/deck-builder
sleep 10s
docker service update --detach=false --image abstractalchemist/deck-builder deck-builder
