#!/bin/bash

TAG=$(git tag | tail -n -1)


#git stash pop
npm i
gulp js
docker build -t abstractalchemist/deck-builder:$TAG -f Dockerfile .
docker push abstractalchemist/deck-builder:$TAG
sleep 10s
docker service update --detach=false --image abstractalchemist/deck-builder:$TAG deck-builder
