version: "3"
services:
   deck-builder-app:
      image: abstractalchemist/deck-builder:v1.0.0.2.x64
      ports:
         - "8080:80"
   simulator-app:
      image: abstractalchemist/weiss-sim:v1.0.0.0.x64
      ports:
         - "8081:80"
   weiss-assist-app:
      image:abstractalchemist/attribute-tracker:x64_v3
      ports:
         - "8082:80"
   deck-builder:
      image: couchdb
      volumes:
         - "deck-data:/usr/local/var/lib/couchdb"
      ports:
         - "5984:5984"
networks:
   deck-network:
volumes:
   deck-data: